### ISSUE TITLE
Settings not being applied in 2.1.0

### ISSUE THREAD

**Issue by jeliastam** [vanossj/deluge-seedtime#11]
initially, I saw an error in the deluge log for `config/seedtime.conf` not existing, so I created it.  

The error went away and settings seemed to be saving but the config was still empty.  

I manually added defaults and adjusted them, but that had to affect.  I have no idea where the settings are being stored, but regardless of the values, the column values for seed time and remaining time do not update.

**Comment by vanossj** [comment]
the `seedtime.conf` file should be in the [deluge config directory](https://dev.deluge-torrent.org/wiki/Faq#WheredoesDelugestoreitssettingsconfig). 

Default locations:
* Windows: `%APPDATA%\deluge\seedtime.conf`
* Linux/Mac: `~/.config/deluge/seedtime.conf`

This file should change when you change the plugin settings.

The `seedtime.conf` file with default settings should look like this
```
{
    "file": 1,
    "format": 1
}{
    "default_stop_time": 7,
    "delay_time": 1,
    "filter_list": [],
    "remove_torrent": false,
    "torrent_stop_times": {}
}
```

If you modify the values in the file instead of through the UI (not recommended), you will probably have to restart the deluge client and server for it to reread the file and apply the new values.

**Comment by jeliastam** [comment]
ah I was missing the first object... thank you!

I think the config path is a little different because im using the linuxserver.io deluge docker on unraid.

ok got the conf file working... but I am still see 0's for `Stop Seed Time` and `Remaining Seed Time` for everything.

![image](https://user-images.githubusercontent.com/2113009/135701647-355f81a5-873d-46b6-b0c7-016706b5b513.png)


I think this plugin is a great and would love to get it working.

**Comment by vanossj** [comment]
hmm, there should be a default filter added but there doesn't appear to be one. Press the Add button, then change the filter to `.*` as a catch all. You can add other filters by following the [instructions here](https://github.com/vanossj/deluge-seedtime#using-the-plugin).

![image](https://user-images.githubusercontent.com/8310169/135701819-621a2877-2040-4724-98a7-fa4e0d709389.png)

**Comment by jeliastam** [comment]
So when I try to do that, both inputs (filter and time) have a filled in
red corner like the input is invalid or something.  I can send a pic in the
morning, if needed.

Thanks

**Comment by jeliastam** [comment]
ah it actually looks like its working when I add a new torrent, ok I just
have to manually update the existing ones.

thanks again
