### ISSUE TITLE
Missing from preferences list

### ISSUE THREAD

**Issue by WildIsTheWind** [vanossj/deluge-seedtime#9]
Installing doesn't seem to add the plugin options to the preferences sidebar...

I know this is pretty old, but it's newer than the plugin it was forked from. Hopefully it's still compatible with Deluge.

![ss](https://user-images.githubusercontent.com/65055132/81461841-697d1a00-917c-11ea-93c2-2e54aa4cedb4.jpg)

(FYI: Win10, Deluge 1.3.15)

**Comment by vanossj** [comment]
I'll look into it but the quicker solution might be to try using the previous plugin version (v2.0).

The newest plugin version just added support for Deluge 2.0, but you can't even use that version on windows.

Since its going to be an old version the uninstall might be a bit more involved.
1. uncheck the Enabled checkbox in the plugins preferences window.
2. go to %APPDATA%/deluge in windows explorer
3. delete any _seedtime.conf_ and _seedtime.conf~ files_
4. go into the plugin folder and delete _SeedTime-2.1.0-py2.7.egg_
5. download Seedtime 2.0 egg and install it in deluge with the normal install plugin button

let me know if you still have issues with it. You're aren't missing out on any features by using the older plugin version

**Comment by WildIsTheWind** [comment]
Yep, 2.0.0 shows up. Can't say for sure if it works yet, since I haven't added any new torrents yet, but assume it does unless you hear otherwise.

Thanks.
